name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDKROOT: ${{ secrets.ANDROIDSDKROOT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer
          
      - name: Download Android cmdline-tools
        run: |
          mkdir -p $ANDROIDSDKROOT/cmdline-tools
          cd $ANDROIDSDKROOT/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -o commandlinetools.zip
          mv cmdline-tools latest

      - name: Accept Android SDK licenses
        run: yes | $ANDROIDSDKROOT/cmdline-tools/latest/bin/sdkmanager --licenses
   

      - name: Accept Android SDK licenses
        run: yes | $ANDROIDSDKROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android SDK packages
        run: |
          $ANDROIDSDKROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;33.0.2" "platforms;android-33" "cmdline-tools;latest"

      - name: Build APK
        run: |
          cd starter_app
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk

