name: Android SDK Setup Test

on:
  push:
    branches:
      - main

jobs:
  sdk-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set ANDROIDSDKROOT env
        run: echo "ANDROIDSDKROOT=/home/runner/Android" >> $GITHUB_ENV

      - name: Download Command Line Tools
        run: |
          mkdir -p $ANDROIDSDKROOT/cmdline-tools
          cd $ANDROIDSDKROOT/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest
          rm cmdline-tools.zip

      - name: Install Android SDK packages
        run: |
          yes | $ANDROIDSDKROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDKROOT --licenses
          $ANDROIDSDKROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDKROOT "platform-tools" "build-tools;33.0.2" "platforms;android-33"

      - name: List installed SDK packages
        run: $ANDROIDSDKROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDKROOT --list_installed
