name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Cython
        run: pip install cython==0.29.36

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer
        env:
          ANDROIDSDKROOT: ${{ secrets.ANDROIDSDKROOT }}

      - name: Install Android SDK build tools and platform tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "build-tools;33.0.0" "platforms;android-33"
        env:
          ANDROIDSDKROOT: ${{ secrets.ANDROIDSDKROOT }}

      - name: Build APK
        run: |
          cd starter_app
          buildozer android debug
        env:
          ANDROIDSDKROOT: ${{ secrets.ANDROIDSDKROOT }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk


